# Generated by Django 4.1.3 on 2022-12-07 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_date_watclist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 14, 51, 4, 297470)),
        ),
        migrations.AlterField(
            model_name='watclist',
            name='items',
            field=models.ManyToManyField(related_name='related_watchlists', to='auctions.auction'),
        ),
    ]
