# Generated by Django 4.1.3 on 2022-12-12 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_is_open_alter_auction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=26)),
                ('description', models.CharField(max_length=126)),
                ('img_url', models.CharField(max_length=126)),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 16, 47, 50, 16809)),
        ),
    ]
