# Generated by Django 4.1.3 on 2022-12-12 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_category_alter_auction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 16, 48, 30, 606529)),
        ),
    ]
